# Generated by Django 3.2.5 on 2021-07-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_alter_transcations_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcations',
            name='dt',
        ),
    ]
