# Generated by Django 3.2.5 on 2021-07-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_remove_transcations_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
